# Generated by Django 4.2.14 on 2026-02-23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Redirect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_path', models.CharField(help_text='Old URL path (e.g., /product/old-slug or /category/old-slug)', max_length=500, unique=True)),
                ('new_path', models.CharField(help_text='New URL path (e.g., /product/new-slug or /category/new-slug)', max_length=500)),
                ('redirect_type', models.CharField(choices=[('product', 'Product'), ('category', 'Category'), ('blog', 'Blog'), ('manual', 'Manual')], default='manual', help_text='Type of redirect', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='redirect',
            index=models.Index(fields=['old_path'], name='core_redire_old_pat_e93f1f_idx'),
        ),
        migrations.AddIndex(
            model_name='redirect',
            index=models.Index(fields=['is_active', 'old_path'], name='core_redire_is_acti_7fe4e2_idx'),
        ),
    ]
