# Generated by Django 4.2.14 on 2025-10-07 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='content',
            field=models.TextField(help_text='Blog post content. Can be plain text or HTML.'),
        ),
    ]
