# Generated by Django 4.2.14 on 2026-02-21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('blog', '0002_alter_blogpost_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='related_categories',
            field=models.ManyToManyField(blank=True, help_text='Furniture categories this post supports.', related_name='blog_posts', to='products.roomcategory'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='related_products',
            field=models.ManyToManyField(blank=True, help_text='Products referenced by this post for SEO interlinking.', related_name='blog_posts', to='products.product'),
        ),
    ]
